name: React CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:  

jobs:
  install-and-build:
    name: Install & Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'  


    - name: Install dependencies
      run: npm ci  


    - name: Build production bundle
      run: npm run build


    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GH_PAGES_DEPLOY_TOKEN }}  
        publish_dir: ./build
        publish_branch: gh-pages
        keep_files: false 